### ISSUE TITLE
Allow additional domains to be added

### ISSUE THREAD

**Issue by maudrid** [ubercow/bandcamp_volume#8]
Some bandcamp pages have custom domains .
The volume control does not show up on these pages.
Suggestion: Allow additional domains to be added in the plugin settings.

**Comment by josh-bridge** [comment]
Doing this would mean requiring access to every website you visit, and run a check on every single page you visit to see if it is a bandcamp page (which even though it wouldn't store that information, is not something that you really want happening for page load time reasons and privacy reasons)

This is not something that should be done globally on the extension, and not worth the time to develop for the very small amount of people that would use this feature. However you're welcome to add it yourself, as the code is open source! Learning Javascript can be fun! (sometimes)

**Comment by helloitszak** [comment]
The alternative to this would be, as you suggested, manual entry of each domain. The extension would still require access to any page, but I think it's possible to get the current domain from the extension code and only inject the script on a match. This would eliminate the load time concern, though it would require the user to manually add domains in the settings or something.

However, I'm still reluctant to do this due to the privacy concerns of having the plugin be able to access every page. I personally get really suspicious when an existing extension suddenly asks for access to everything, when they only needed one domain in the past.

I'm open to discussion though, as this is a feature I would personally love.
